import typescript from "rollup-plugin-typescript2";
import packagejson from "./package.json";

export default {
  input: "./index.ts",
  plugins: [typescript(/*{ plugin options }*/)],
  output: {
    intro: `
/*
    Finicky Config API ${packagejson.version}
    This file is automatically generated. Please refer to the \`config-api\` folder to build a new one.
*/`,
    file: "../Finicky/Finicky/finickyConfigAPI.js",
    format: "iife",
    name: "finickyConfigApi",
    noInterop: true
  }
  //external: ["react", "styled-components"]
};
