import fs from "fs";
import { ZodToTypescript } from "@duplojs/zod-to-typescript";
import { ConfigSchema } from "../src/configSchema.ts";

const tsType = ZodToTypescript.convert(ConfigSchema, {
  name: "FinickyConfig",
  export: true,
});

// TODO: Generate the FinickyUtils interface automatically
const output = `
/** This file is generated by the generate-typedefs.ts script. Do not edit it directly. */

interface FinickyUtils {
    matchHostnames: (hostnames: string[]) => (url: URL) => boolean;
    getModifierKeys: () => {
        shift: boolean;
        option: boolean;
        command: boolean;
        control: boolean;
        capsLock: boolean;
        fn: boolean;
    };
    getSystemInfo: () => {
        localizedName: string;
        name: string;
    };
}

declare global {
    const finicky: FinickyUtils
}

export ${tsType}
`;

fs.writeFileSync("../assets/Resources/finicky.d.ts", output, "utf-8");
